### ISSUE TITLE
Request: in sample, show how to compress and decompress, including getting inner file info (size and name)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [luben/ZstdAndroidExample#1]
As the title says...

**Comment by luben** [comment]
Zstd is purely compression algorithm so it does not keep track of inner file name, may or may not contain the original size.

This project is a showcase how to setup an Android project that uses Zstd-jni. I don't think it should contain anything else.

**Comment by AndroidDeveloperLB** [comment]
It's not? So how do you know to which file name to decompress it to? Same as its own? 
Doesn't it mean that in order to use it properly, one has to use an additional step, to compress/package file/s into a single one, and only then compress to Zstd?

**Comment by luben** [comment]
Yes, people usually use `tar` to back files together. Then they compress them with `zstd`.

The CLI behaviour when compressing/decompressing is to use the same file just adding/removing the `.zst` extension.

**Comment by AndroidDeveloperLB** [comment]
I see. But if it's 2 steps, would it still be possible to go over the files inside, without extracting them all? 
Meaning using perhaps the InputStream?
Or would such a thing require either extracting or loading it all into memory?

**Comment by luben** [comment]
Yes, you will need first to decompress the file then follow with tar (or other format) extractor.

**Comment by AndroidDeveloperLB** [comment]
Meaning to create real files? Too bad.

**Comment by luben** [comment]
It depends on the internal format, but the intermediate results can be in memory only.

**Comment by AndroidDeveloperLB** [comment]
I see, but in general Zstd does allow getting the stream without creating real file, right?

**Comment by luben** [comment]
Yes, there is `ZstdInputStream` for decompressing.

**Comment by AndroidDeveloperLB** [comment]
OK thank you.
