### ISSUE TITLE
Not working in real device

### ISSUE THREAD

**Issue by bolds07** [luben/ZstdAndroidExample#2]
I've followed all the instructions but it is not working in real android devices.

i've added to build.gradle
```
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()

    }
}
```
and
 `implementation 'com.github.luben:zstd-jni:1.4.8-4@aar'`

it does work in the emulator (arc x86_64) and in my windows java (importing the jar from maven) but when i deploy to real android devices it doesn't find the libs for specific arc

i got errors like:

```
   at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.github.luben.zstd.util.Native.load(Native.java:85)
       at com.github.luben.zstd.util.Native.load(Native.java:55)
       at com.github.luben.zstd.ZstdInputStreamNoFinalizer.<clinit>(ZstdInputStreamNoFinalizer.java:23)
       at com.tomatedigital.okhttp.interceptors.ContentEncoderInterceptor.intercept(ContentEncoderInterceptor.java:84)
,,, omiting very long stack trace since this is the relevant part
```

the error says
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader /lib/arm, /system/lib, /vendor/lib]]] couldn't find "libzstd-jni.so"
Unsupported OS/arch, cannot find /linux/armv7l/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
```

depending on the phone the path changes he also complains about =/lib/arm64, /system/lib64, /vendor/lib64

then i looked and saw that the packing is for x86, x86_64, armeabi-v7a and arm64-v8a.

So what are the minimum requirements for android plataforms to use the lib?

**Comment by bolds07** [comment]
The problem was related to proguard files. added a rule for this library and it started working

**Comment by luben** [comment]
Glad you solved it. On you another question - it should work on anything >= Android-4.1(SDK version 16) and  it is optimized for Android 8 (SDK v26). I don't remember why exactly I used v16 but I tried to go as low as possible. I think it was due to some NDK changes.
